src/Entity/Lodging.php
<?php

namespace App\Entity;

use App\Repository\LodgingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LodgingRepository::class)]
class Lodging
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $adress = null;

    #[ORM\Column]
    private ?float $price_per_night = null;

    #[ORM\Column]
    private ?bool $animals_allowed = null;

    #[ORM\Column]
    private ?int $simple_bed_count = null;

    #[ORM\Column]
    private ?int $double_bed_count = null;

    #[ORM\Column]
    private ?int $bedroom_count = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'lodgings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?LodgingCategory $lodging_category = null;

    /**
     * @var Collection<int, Reservation>
     */
    #[ORM\OneToMany(targetEntity: Reservation::class, mappedBy: 'lodge')]
    private Collection $reservations;

    /**
     * @var Collection<int, Picture>
     */
    #[ORM\OneToMany(targetEntity: Picture::class, mappedBy: 'lodge')]
    private Collection $pictures;

    /**
     * @var Collection<int, Amenities>
     */
    #[ORM\ManyToMany(targetEntity: Amenities::class, inversedBy: 'lodgings')]
    private Collection $amenities;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->amenities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPricePerNight(): ?float
    {
        return $this->price_per_night;
    }

    public function setPricePerNight(float $price_per_night): static
    {
        $this->price_per_night = $price_per_night;

        return $this;
    }

    public function isAnimalsAllowed(): ?bool
    {
        return $this->animals_allowed;
    }

    public function setAnimalsAllowed(bool $animals_allowed): static
    {
        $this->animals_allowed = $animals_allowed;

        return $this;
    }

    public function getSimpleBedCount(): ?int
    {
        return $this->simple_bed_count;
    }

    public function setSimpleBedCount(int $simple_bed_count): static
    {
        $this->simple_bed_count = $simple_bed_count;

        return $this;
    }

    public function getDoubleBedCount(): ?int
    {
        return $this->double_bed_count;
    }

    public function setDoubleBedCount(int $double_bed_count): static
    {
        $this->double_bed_count = $double_bed_count;

        return $this;
    }

    public function getBedroomCount(): ?int
    {
        return $this->bedroom_count;
    }

    public function setBedroomCount(int $bedroom_count): static
    {
        $this->bedroom_count = $bedroom_count;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLodgingCategory(): ?LodgingCategory
    {
        return $this->lodging_category;
    }

    public function setLodgingCategory(?LodgingCategory $lodging_category): static
    {
        $this->lodging_category = $lodging_category;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setLodge($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getLodge() === $this) {
                $reservation->setLodge(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Picture>
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): static
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures->add($picture);
            $picture->setLodge($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): static
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getLodge() === $this) {
                $picture->setLodge(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Amenities>
     */
    public function getAmenities(): Collection
    {
        return $this->amenities;
    }

    public function addAmenity(Amenities $amenity): static
    {
        if (!$this->amenities->contains($amenity)) {
            $this->amenities->add($amenity);
        }

        return $this;
    }

    public function removeAmenity(Amenities $amenity): static
    {
        $this->amenities->removeElement($amenity);

        return $this;
    }
}

src/Form/LodgingType.php
<?php

namespace App\Form;

use App\Entity\Amenities;
use App\Entity\Lodging;
use App\Entity\LodgingCategory;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LodgingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('adress')
            ->add('price_per_night')
            ->add('animals_allowed')
            ->add('simple_bed_count')
            ->add('double_bed_count')
            ->add('bedroom_count')
            ->add('description')
            ->add('lodging_category', EntityType::class, [
                'class' => LodgingCategory::class,
                'choice_label' => 'id',
            ])
            ->add('amenities', EntityType::class, [
                'class' => Amenities::class,
                'choice_label' => 'id',
                'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Lodging::class,
        ]);
    }
}

src/Controller/LodgingController.php
<?php

namespace App\Controller;

use App\Entity\Lodging;
use App\Form\LodgingType;
use App\Repository\LodgingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/lodging')]
final class LodgingController extends AbstractController
{
    #[Route(name: 'app_lodging_index', methods: ['GET'])]
    public function index(LodgingRepository $lodgingRepository): Response
    {
        return $this->render('lodging/index.html.twig', [
            'lodgings' => $lodgingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_lodging_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $lodging = new Lodging();
        $form = $this->createForm(LodgingType::class, $lodging);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($lodging);
            $entityManager->flush();

            return $this->redirectToRoute('app_lodging_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lodging/new.html.twig', [
            'lodging' => $lodging,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lodging_show', methods: ['GET'])]
    public function show(Lodging $lodging): Response
    {
        return $this->render('lodging/show.html.twig', [
            'lodging' => $lodging,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_lodging_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Lodging $lodging, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LodgingType::class, $lodging);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_lodging_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('lodging/edit.html.twig', [
            'lodging' => $lodging,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lodging_delete', methods: ['POST'])]
    public function delete(Request $request, Lodging $lodging, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lodging->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($lodging);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_lodging_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/lodging/_delete_form.html.twig
<form method="post" action="{{ path('app_lodging_delete', {'id': lodging.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lodging.id) }}">
    <button class="btn">Delete</button>
</form>

templates/lodging/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/lodging/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Lodging{% endblock %}

{% block body %}
    <h1>Edit Lodging</h1>

    {{ include('lodging/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_lodging_index') }}">back to list</a>

    {{ include('lodging/_delete_form.html.twig') }}
{% endblock %}

templates/lodging/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lodging index{% endblock %}

{% block body %}
    <h1>Lodging index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Adress</th>
                <th>Price_per_night</th>
                <th>Animals_allowed</th>
                <th>Simple_bed_count</th>
                <th>Double_bed_count</th>
                <th>Bedroom_count</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lodging in lodgings %}
            <tr>
                <td>{{ lodging.id }}</td>
                <td>{{ lodging.name }}</td>
                <td>{{ lodging.adress }}</td>
                <td>{{ lodging.pricePerNight }}</td>
                <td>{{ lodging.animalsAllowed ? 'Yes' : 'No' }}</td>
                <td>{{ lodging.simpleBedCount }}</td>
                <td>{{ lodging.doubleBedCount }}</td>
                <td>{{ lodging.bedroomCount }}</td>
                <td>{{ lodging.description }}</td>
                <td>
                    <a href="{{ path('app_lodging_show', {'id': lodging.id}) }}">show</a>
                    <a href="{{ path('app_lodging_edit', {'id': lodging.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_lodging_new') }}">Create new</a>
{% endblock %}

templates/lodging/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lodging{% endblock %}

{% block body %}
    <h1>Create new Lodging</h1>

    {{ include('lodging/_form.html.twig') }}

    <a href="{{ path('app_lodging_index') }}">back to list</a>
{% endblock %}

templates/lodging/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lodging{% endblock %}

{% block body %}
    <h1>Lodging</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ lodging.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ lodging.name }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ lodging.adress }}</td>
            </tr>
            <tr>
                <th>Price_per_night</th>
                <td>{{ lodging.pricePerNight }}</td>
            </tr>
            <tr>
                <th>Animals_allowed</th>
                <td>{{ lodging.animalsAllowed ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Simple_bed_count</th>
                <td>{{ lodging.simpleBedCount }}</td>
            </tr>
            <tr>
                <th>Double_bed_count</th>
                <td>{{ lodging.doubleBedCount }}</td>
            </tr>
            <tr>
                <th>Bedroom_count</th>
                <td>{{ lodging.bedroomCount }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ lodging.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_lodging_index') }}">back to list</a>

    <a href="{{ path('app_lodging_edit', {'id': lodging.id}) }}">edit</a>

    {{ include('lodging/_delete_form.html.twig') }}
{% endblock %}